modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ftbbackups2"
version = "${version}"
displayName = "FTB Backups 2"
authors = "CreeperHost"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
Backup all the things!
'''
#logoFile = ""

[[dependencies.ftbbackups2]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.ftbbackups2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.ftbbackups2]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.ftbbackups2]]
modId = "polylib"
mandatory = true
versionRange = "[1900.0.2,)"
ordering = "AFTER"
side = "SERVER"
