modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ftbbackups2"
version = "${version}"
displayName = "FTB Backups 2"
authors = "CreeperHost"
description = '''
Backup all the things!
'''
#logoFile = ""

[[dependencies.ftbbackups2]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbbackups2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbbackups2]]
modId = "architectury"
mandatory = true
versionRange = "[5.5.16,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbbackups2]]
modId = "polylib"
mandatory = true
versionRange = "[1900.0.2,)"
ordering = "AFTER"
side = "BOTH"
