modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "ftbbackups2"
version = "${version}"
displayName = "FTB Backups 2"
authors = "CreeperHost"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
Backup all the things!
'''
#logoFile = ""

[[dependencies.ftbbackups2]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbbackups2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbbackups2]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.17,)"
ordering = "AFTER"
side = "BOTH"
